# Generated by Django 4.1 on 2022-09-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="symbol",
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
